"""Basket

Revision ID: 70297441d561
Revises: 3ed1066e21df
Create Date: 2024-09-29 10:37:09.105796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70297441d561'
down_revision: Union[str, None] = '23d67115d520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_history',
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('list_food', sa.String(), nullable=False),
    sa.Column('list_set', sa.String(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('food', 'set')", name='check_valid_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_history_food')
    op.drop_table('users_history_set')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_history_set',
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], name='users_history_set_set_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_history_set_user_id_fkey'),
    sa.PrimaryKeyConstraint('date', name='users_history_set_pkey')
    )
    op.create_table('users_history_food',
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='users_history_food_food_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_history_food_user_id_fkey'),
    sa.PrimaryKeyConstraint('date', name='users_history_food_pkey')
    )
    op.drop_table('basket')
    op.drop_table('users_history')
    # ### end Alembic commands ###
