"""news image

Revision ID: 846275aedc2e
Revises: a971e307a9c6
Create Date: 2024-10-10 22:07:35.849963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846275aedc2e'
down_revision: Union[str, None] = 'a971e307a9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'news', ['image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('news', 'image_url')
    # ### end Alembic commands ###
