"""add constrairs

Revision ID: c4e02447874f
Revises: f4bb4ee07f14
Create Date: 2024-09-30 21:49:15.579265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e02447874f'
down_revision: Union[str, None] = 'f4bb4ee07f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_user_id_fkey', 'basket', type_='foreignkey')
    op.create_foreign_key(None, 'basket', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_address_user_id_fkey', 'user_address', type_='foreignkey')
    op.create_foreign_key(None, 'user_address', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_favorite_food_user_id_fkey', 'users_favorite_food', type_='foreignkey')
    op.create_foreign_key(None, 'users_favorite_food', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_favorite_set_user_id_fkey', 'users_favorite_set', type_='foreignkey')
    op.create_foreign_key(None, 'users_favorite_set', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'users_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_history', type_='foreignkey')
    op.alter_column('users_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'users_favorite_set', type_='foreignkey')
    op.create_foreign_key('users_favorite_set_user_id_fkey', 'users_favorite_set', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_favorite_food', type_='foreignkey')
    op.create_foreign_key('users_favorite_food_user_id_fkey', 'users_favorite_food', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.create_foreign_key('user_address_user_id_fkey', 'user_address', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.create_foreign_key('basket_user_id_fkey', 'basket', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
