"""Database Creation

Revision ID: d2d1b60b3f98
Revises: 72cd38350ed1
Create Date: 2024-09-26 14:16:51.062623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d1b60b3f98'
down_revision: Union[str, None] = '72cd38350ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_favorite', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_favorite', 'type')
    # ### end Alembic commands ###
